using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Research.Genetics.Tabs;


namespace Content.Client.Research.Genetics.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class GeneTekResearchTab : Control
    {

        private readonly StyleBoxFlat _styleBox = new()
        {
            BackgroundColor = Color.FromHex("#1B1B1E"),
        };
        public GeneTekResearchTab()
        {
            RobustXamlLoader.Load(this);
            ResearchListPanel.PanelOverride = _styleBox;
        }

        public void SetMutationsResearched(int count)
        {
            MutationsResearchedLabel.Text = $"Mutations Researched: {count}";
        }

        public void ClearResearchList()
        {
            ResearchList.DisposeAllChildren();
        }

        public void AddResearchEntry(Control entry)
        {
            ResearchList.AddChild(entry);
        }
    }
}
