using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System.Numerics;
using System.Collections.Generic;

namespace Content.Client.Research.Genetics.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class GeneTekSequencerTab : Control
    {
        private readonly StyleBoxFlat _styleBox = new()
        {
            BackgroundColor = Color.FromHex("#1B1B1E"),
        };

        public GeneTekSequencerTab()
        {
            RobustXamlLoader.Load(this);

            PopulateGenomeGrid(GridContainerGenome0);
            PopulateGenomeGrid(GridContainerGenome1);
            PopulateGenomeGrid(GridContainerGenome2);
            PopulateGenomeGrid(GridContainerGenome3);
        }

        private void PopulateGenomeGrid(GridContainer container)
        {
            var pairs = new List<(char, char)>
            {
                ('G', 'C'),
                ('A', 'T'),
                ('X', 'G'),
                ('T', 'A'),
                ('X', 'X')
            };

            foreach (var (first, second) in pairs)
            {
                if (IsValidPair(first, second))
                    AddPairToGrid(container, first, second);
            }
        }

        private void AddPairToGrid(GridContainer container, char top, char bottom)
        {
            var btnTop = new Button
            {
                Text = top.ToString(),
                MinSize = new Vector2(15, 15)
            };

            var btnBottom = new Button
            {
                Text = bottom.ToString(),
                MinSize = new Vector2(15, 15)
            };

            ColorButton(btnTop);
            ColorButton(btnBottom);

            container.AddChild(btnTop);
            container.AddChild(btnBottom);
        }

        private bool IsValidPair(char a, char b)
        {
            return (a == 'A' && b == 'T') ||
                (a == 'T' && b == 'A') ||
                (a == 'G' && b == 'C') ||
                (a == 'C' && b == 'G') ||
                (a == 'X' && b == 'X') ||
                (a == 'X' && b == 'G') ||
                (a == 'G' && b == 'X');
        }

        private void ColorButton(Button button)
        {
            switch (button.Text)
            {
                case "G":
                    button.Modulate = Color.FromHex("#00FF00");
                    break;
                case "T":
                    button.Modulate = Color.FromHex("#00AAFF");
                    break;
                case "C":
                    button.Modulate = Color.FromHex("#FFA500");
                    break;
                case "A":
                    button.Modulate = Color.FromHex("#00DDDD");
                    break;
                case "X":
                    button.Modulate = Color.FromHex("#AAAAAA");
                    break;
            }
        }

        public void SetSequenceInfoLabel(string info)
        {
            sequenceinfolabel.Text = $"Name: {info}";
        }
    }
}
