using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Research.Components;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Utility;
using System;

namespace Content.Client.Research.UI;
[GenerateTypedNameReferences]
public sealed partial class DataRecoveryMenu : FancyWindow
{
    public event Action<int>? OnBitToggled;
    public event Action? OnConfirmPressed;

    private readonly Button[] BitButtons = new Button[40];

    public DataRecoveryMenu()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => OnConfirmPressed?.Invoke();

        BitButtons[0] = Bit0;
        BitButtons[1] = Bit1;
        BitButtons[2] = Bit2;
        BitButtons[3] = Bit3;
        BitButtons[4] = Bit4;
        BitButtons[5] = Bit5;
        BitButtons[6] = Bit6;
        BitButtons[7] = Bit7;
        BitButtons[8] = Bit8;
        BitButtons[9] = Bit9;
        BitButtons[10] = Bit10;
        BitButtons[11] = Bit11;
        BitButtons[12] = Bit12;
        BitButtons[13] = Bit13;
        BitButtons[14] = Bit14;
        BitButtons[15] = Bit15;
        BitButtons[16] = Bit16;
        BitButtons[17] = Bit17;
        BitButtons[18] = Bit18;
        BitButtons[19] = Bit19;
        BitButtons[20] = Bit20;
        BitButtons[21] = Bit21;
        BitButtons[22] = Bit22;
        BitButtons[23] = Bit23;
        BitButtons[24] = Bit24;
        BitButtons[25] = Bit25;
        BitButtons[26] = Bit26;
        BitButtons[27] = Bit27;
        BitButtons[28] = Bit28;
        BitButtons[29] = Bit29;
        BitButtons[30] = Bit30;
        BitButtons[31] = Bit31;
        BitButtons[32] = Bit32;
        BitButtons[33] = Bit33;
        BitButtons[34] = Bit34;
        BitButtons[35] = Bit35;
        BitButtons[36] = Bit36;
        BitButtons[37] = Bit37;
        BitButtons[38] = Bit38;
        BitButtons[39] = Bit39;


        for (int i = 0; i < 40; i++)
        {
            var bitButton = BitButtons[i];
            var index = i; // evitar closure bug
            bitButton.OnPressed += _ => OnBitToggled?.Invoke(index);
        }
    }

    public void UpdateUI(DataRecoveryBoundUserInterfaceState state)
    {
        for (int i = 0; i < state.Bytes.Length; i++)
        {
            BitButtons[i].ToggleMode = true;
            BitButtons[i].Pressed = state.Bytes[i];
            BitButtons[i].Modulate = state.ErrorMask[i] ? Color.Red : Color.White;
        }

        ConfirmButton.Disabled = !state.CanConfirm;
    }
}
