using Content.Client.UserInterface.Controls;
using Content.Shared.Research.Genetics;
using Content.Client.Research.Genetics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Content.Client.Research.Genetics.Tabs;


namespace Content.Client.Research.Genetics;

[GenerateTypedNameReferences]
public sealed partial class GeneTekConsoleMenu : FancyWindow
{
    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#102B2C"),
    };

    public GeneTekConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        OccupantNamePanel.PanelOverride = _styleBox;
    }

    public void Update(GeneTekConsoleBoundUserInterfaceState state)
    {
        // Atualiza o painel lateral (ocupante, vida, etc.)
        OccupantName.Text = state.OccupantName ?? "None";
        HealthBar.Value = state.Health;
        StabilityBar.Value = state.Stability;
        InjectorsLabel.Text = $"Injectors: {(state.InjectorsReady ? "Ready" : "Not Ready")}";
        EmitterLabel.Text = $"Emitter: {(state.EmitterReady ? "Ready" : "Not Ready")}";

        foreach (var research in state.AvailableResearch)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2),
            };

            var label = new Label
            {
                Text = research.Name,
                HorizontalExpand = true
            };

            var button = new Button
            {
                Text = $"Research ({research.Cost} mat, {research.Duration}s)",
                Disabled = research.Cost > state.MaterialsCurrent
            };

            // Aqui você pode conectar o botão ao envio de mensagem pro servidor

            row.AddChild(label);
            row.AddChild(button);
        }
    }
}
